from dataclasses import dataclass, field
from datetime import datetime, time, timedelta
from typing import Optional
import hashlib

@dataclass
class User:
    """
    User data model with authentication and time budget info
    
    Attributes:
        id: User ID (auto-generated by database)
        username: Unique username
        email: User email (optional)
        password_hash: Hashed password (never store plaintext!)
        role: User role (admin, premium, user)
        full_name: User's full name
        profile_photo: Path to profile photo (optional)
        
        # Time budget settings
        sleep_hours: Hours of sleep per day
        wake_time: When user's day starts (e.g., "07:00")
        has_work: Whether user has a job
        work_hours_per_week: Total work hours per week
        work_days_per_week: Days worked per week
        study_goal_hours_per_day: Daily study goal in hours
        
        # Account status
        is_active: Account enabled/disabled
        is_locked: Account locked (security)
        failed_login_attempts: Track failed logins
        
        # Timestamps
        created_at: Account creation timestamp
        updated_at: Last update timestamp
        last_login: Last successful login
    """
    
    # Required fields
    username: str
    password_hash: str
    role: str = "user"
    
    # Optional fields
    id: Optional[int] = None
    email: Optional[str] = None
    full_name: Optional[str] = None
    profile_photo: Optional[str] = None
    
    # Time budget settings (from onboarding)
    sleep_hours: float = 8.0
    wake_time: str = "07:00"  # 24-hour format HH:MM
    has_work: bool = False
    work_hours_per_week: float = 0.0
    work_days_per_week: int = 0
    study_goal_hours_per_day: float = 0.0
    
    # Account status
    is_active: bool = True
    is_locked: bool = False
    failed_login_attempts: int = 0
    
    # Timestamps
    created_at: Optional[str] = None
    updated_at: Optional[str] = None
    last_login: Optional[str] = None
    
    def __post_init__(self):
        """Initialize timestamps if not provided"""
        now = datetime.now().isoformat()
        if not self.created_at:
            self.created_at = now
        if not self.updated_at:
            self.updated_at = now
    
    @staticmethod
    def hash_password(password: str) -> str:
        """
        Hash a password using SHA-256
        
        Args:
            password: Plain text password
            
        Returns:
            Hashed password string
        """
        return hashlib.sha256(password.encode()).hexdigest()
    
    def verify_password(self, password: str) -> bool:
        """
        Verify password matches stored hash
        
        Args:
            password: Plain text password to verify
            
        Returns:
            True if password matches, False otherwise
        """
        return self.password_hash == self.hash_password(password)
    
    # ==================== DATABASE METHODS ====================
    
    def to_dict(self) -> dict:
        """
        Convert user to dictionary (for database storage)
        
        Returns:
            Dictionary representation of user
        """
        return {
            "id": self.id,
            "username": self.username,
            "email": self.email,
            "password_hash": self.password_hash,
            "role": self.role,
            "full_name": self.full_name,
            "profile_photo": self.profile_photo,
            "sleep_hours": self.sleep_hours,
            "wake_time": self.wake_time,
            "has_work": 1 if self.has_work else 0,
            "work_hours_per_week": self.work_hours_per_week,
            "work_days_per_week": self.work_days_per_week,
            "study_goal_hours_per_day": self.study_goal_hours_per_day,
            "is_active": 1 if self.is_active else 0,
            "is_locked": 1 if self.is_locked else 0,
            "failed_login_attempts": self.failed_login_attempts,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
            "last_login": self.last_login,
        }
    
    @classmethod
    def from_dict(cls, data: dict) -> 'User':
        """
        Create User instance from dictionary (from database)
        
        Args:
            data: Dictionary with user data
            
        Returns:
            User instance
        """
        return cls(
            id=data.get("id"),
            username=data["username"],
            email=data.get("email"),
            password_hash=data["password_hash"],
            role=data.get("role", "user"),
            full_name=data.get("full_name"),
            profile_photo=data.get("profile_photo"),
            sleep_hours=float(data.get("sleep_hours", 8.0)),
            wake_time=data.get("wake_time", "07:00"),
            has_work=bool(data.get("has_work", 0)),
            work_hours_per_week=float(data.get("work_hours_per_week", 0.0)),
            work_days_per_week=int(data.get("work_days_per_week", 0)),
            study_goal_hours_per_day=float(data.get("study_goal_hours_per_day", 0.0)),
            is_active=bool(data.get("is_active", 1)),
            is_locked=bool(data.get("is_locked", 0)),
            failed_login_attempts=int(data.get("failed_login_attempts", 0)),
            created_at=data.get("created_at"),
            updated_at=data.get("updated_at"),
            last_login=data.get("last_login"),
        )
    
    def has_permission(self, permission: str) -> bool:
        """
        Check if user has a specific permission based on role
        
        Args:
            permission: Permission to check
            
        Returns:
            True if user has permission
        """
        # Admin has all permissions
        if self.role == "admin":
            return True
        
        # Define permissions per role
        role_permissions = {
            "premium": [
                "create_tasks", "view_analytics", "smart_tips",
                "file_upload", "unlimited_tasks"
            ],
            "user": [
                "create_tasks", "view_own_analytics", "file_upload"
            ]
        }
        
        return permission in role_permissions.get(self.role, [])
    
    def __repr__(self) -> str:
        """String representation for debugging"""
        return f"User(id={self.id}, username='{self.username}', role='{self.role}')"


# Example usage
if __name__ == "__main__":
    # Create a new user
    user = User(
        username="jessica",
        password_hash=User.hash_password("jessica123"),
        email="jessica@example.com",
        full_name="Jessica Lanuzo",
        role="premium",
        sleep_hours=7.5,
        wake_time="06:30",
        has_work=True,
        work_hours_per_week=20,
        work_days_per_week=4,
        study_goal_hours_per_day=5.0,
    )
    
    print(user)
    print(f"Has permission to view smart tips: {user.has_permission('smart_tips')}")
    
    # Verify password
    print(f"\nPassword correct: {user.verify_password('jessica123')}")
    print(f"Wrong password: {user.verify_password('wrong')}")
    
    print("\nNote: Use OnboardingManager for all time budget calculations!")